spring:
  autoconfigure:
    exclude: import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    password: 123456
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false